// Mocks generated by Mockito 5.4.6 from annotations
// in day_break/test/settings_screen_gps_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:day_break/services/location_service.dart' as _i7;
import 'package:geolocator/geolocator.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:hive/hive.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_1 extends _i1.SmartFake implements _i3.Position {
  _FakePosition_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i4.Box<E> {
  @override
  Iterable<E> get values =>
      (super.noSuchMethod(
            Invocation.getter(#values),
            returnValue: <E>[],
            returnValueForMissingStub: <E>[],
          )
          as Iterable<E>);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  bool get isOpen =>
      (super.noSuchMethod(
            Invocation.getter(#isOpen),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get lazy =>
      (super.noSuchMethod(
            Invocation.getter(#lazy),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<dynamic> get keys =>
      (super.noSuchMethod(
            Invocation.getter(#keys),
            returnValue: <dynamic>[],
            returnValueForMissingStub: <dynamic>[],
          )
          as Iterable<dynamic>);

  @override
  int get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNotEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isNotEmpty),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<E> valuesBetween({dynamic startKey, dynamic endKey}) =>
      (super.noSuchMethod(
            Invocation.method(#valuesBetween, [], {
              #startKey: startKey,
              #endKey: endKey,
            }),
            returnValue: <E>[],
            returnValueForMissingStub: <E>[],
          )
          as Iterable<E>);

  @override
  E? getAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#getAt, [index]),
            returnValueForMissingStub: null,
          )
          as E?);

  @override
  Map<dynamic, E> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <dynamic, E>{},
            returnValueForMissingStub: <dynamic, E>{},
          )
          as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(
    Invocation.method(#keyAt, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Stream<_i4.BoxEvent> watch({dynamic key}) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {#key: key}),
            returnValue: _i6.Stream<_i4.BoxEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i4.BoxEvent>.empty(),
          )
          as _i6.Stream<_i4.BoxEvent>);

  @override
  bool containsKey(dynamic key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> put(dynamic key, E? value) =>
      (super.noSuchMethod(
            Invocation.method(#put, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> putAt(int? index, E? value) =>
      (super.noSuchMethod(
            Invocation.method(#putAt, [index, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> putAll(Map<dynamic, E>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#putAll, [entries]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> add(E? value) =>
      (super.noSuchMethod(
            Invocation.method(#add, [value]),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<Iterable<int>> addAll(Iterable<E>? values) =>
      (super.noSuchMethod(
            Invocation.method(#addAll, [values]),
            returnValue: _i6.Future<Iterable<int>>.value(<int>[]),
            returnValueForMissingStub: _i6.Future<Iterable<int>>.value(<int>[]),
          )
          as _i6.Future<Iterable<int>>);

  @override
  _i6.Future<void> delete(dynamic key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAt, [index]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAll(Iterable<dynamic>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [keys]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> compact() =>
      (super.noSuchMethod(
            Invocation.method(#compact, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteFromDisk() =>
      (super.noSuchMethod(
            Invocation.method(#deleteFromDisk, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> flush() =>
      (super.noSuchMethod(
            Invocation.method(#flush, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i7.LocationService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<_i3.Position> determinePosition() =>
      (super.noSuchMethod(
            Invocation.method(#determinePosition, []),
            returnValue: _i6.Future<_i3.Position>.value(
              _FakePosition_1(this, Invocation.method(#determinePosition, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.Position>.value(
              _FakePosition_1(this, Invocation.method(#determinePosition, [])),
            ),
          )
          as _i6.Future<_i3.Position>);

  @override
  _i6.Future<String> getCurrentLocationSuggestion() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocationSuggestion, []),
            returnValue: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getCurrentLocationSuggestion, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getCurrentLocationSuggestion, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InternalFinalCallback].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternalFinalCallback extends _i1.Mock
    implements _i2.InternalFinalCallback<void> {
  @override
  void call() => super.noSuchMethod(
    Invocation.method(#call, []),
    returnValueForMissingStub: null,
  );
}
